# Generated by Django 5.1.3 on 2025-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_specialization_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_model',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default='admin_model', max_length=20),
        ),
    ]
