# Generated by Django 5.1.3 on 2025-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_model_username_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (1, 'admin'), (2, 'doc')], default='admin_model', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='s_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
