# Generated by Django 5.1.3 on 2025-02-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (3, 'patient'), (2, 'doc')], default='admin_model', max_length=20),
        ),
    ]
