# Generated by Django 5.1.3 on 2025-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc'), (3, 'patient')], default='admin_model', max_length=20),
        ),
    ]
