# Generated by Django 5.1.3 on 2025-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (1, 'admin'), (2, 'doc')], default='admin_model', max_length=20),
        ),
    ]
