# Generated by Django 5.1.3 on 2025-02-11 20:22

import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor_model',
            managers=[
                ('objects', hospital.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor_model',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
