# Generated by Django 5.1.3 on 2025-02-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_doctor_model_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor_model',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (2, 'doc'), (1, 'admin')], default='admin_model', max_length=20),
        ),
    ]
