# Generated by Django 5.1.3 on 2025-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), (3, 'patient')], default='admin_model', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor_model',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, max_length=100),
        ),
    ]
