# Generated by Django 5.1.3 on 2025-02-13 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_doctor_model_user_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'patient'), (1, 'admin'), (2, 'doc')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor_model',
            name='username',
            field=models.OneToOneField(default=None, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='hospital.customuser'),
        ),
    ]
