# Generated by Django 5.1.3 on 2025-02-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_model',
            name='username',
            field=models.OneToOneField(default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.customuser'),
        ),
    ]
