# Generated by Django 5.1.3 on 2025-02-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_doctor_model_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (3, 'patient'), (1, 'admin')], default=None, max_length=20),
        ),
    ]
