# Generated by Django 5.1.3 on 2025-02-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('admin', 'admin')], default=None, max_length=20),
        ),
    ]
