# Generated by Django 5.1.3 on 2025-02-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('patient', 'patient')], default=None, max_length=20),
        ),
    ]
