# Generated by Django 5.1.3 on 2025-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_model',
            new_name='doctor',
        ),
    ]
