# Generated by Django 5.1.3 on 2025-02-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_alter_patient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentnumber', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_appointment', models.CharField(max_length=250)),
                ('time_of_appointment', models.CharField(max_length=250)),
                ('additional_msg', models.TextField(blank=True)),
                ('remark', models.CharField(default=0, max_length=250)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Cancelled'), ('3', 'Completed')], default='0', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('pat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('spec_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.specialization')),
            ],
        ),
    ]
