# Generated by Django 5.1.3 on 2025-02-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Cancelled'), ('3', 'Completed')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.OneToOneField(default='Doctor', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
