# Generated by Django 5.1.3 on 2025-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_appointment_status_alter_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentnumber',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
