# Generated by Django 5.1.3 on 2025-03-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
