# Generated by Django 5.1.3 on 2025-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('0', 'new'), ('1', 'Confirmed'), ('2', 'Cancelled'), ('3', 'Completed')], default=0, max_length=200),
        ),
    ]
